# Generated by Django 5.0 on 2023-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('CaegoryImage', models.ImageField(blank=True, null=True, upload_to='Category Image')),
            ],
        ),
    ]
