# Generated by Django 5.0 on 2023-12-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='CaegoryImage',
            new_name='CategoryImage',
        ),
    ]
